const MOVIE_REQUESTED = 'MOVIE_REQUESTED';
const MOVIE_SUCCEEDED = 'MOVIE_SUCCEEDED';
const MOVIE_FAILED = 'MOVIE_FAILED';

const SEARCH_QUERY_CHANGED = 'SEARCH_QUERY_CHANGED';

const DETAILS_REQUESTED = 'DETAILS_REQUESTED';
const DETAILS_SUCCEEDED = 'DETAILS_SUCCEEDED';
const DETAILS_FAILED = 'DETAILS_FAILED';

export default { 
    MOVIE_REQUESTED,
    MOVIE_SUCCEEDED, 
    MOVIE_FAILED,
    SEARCH_QUERY_CHANGED,
    DETAILS_REQUESTED,
    DETAILS_SUCCEEDED,
    DETAILS_FAILED
};