const MOVIE_REQUESTED = 'MOVIE_REQUESTED';
const MOVIE_SUCCEEDED = 'MOVIE_SUCCEEDED';
const MOVIE_FAILED = 'MOVIE_FAILED';

const SEARCH_QUERY_CHANGED = 'SEARCH_QUERY_CHANGED';

export default { 
    MOVIE_REQUESTED,
    MOVIE_SUCCEEDED, 
    MOVIE_FAILED,
    SEARCH_QUERY_CHANGED
};